version: "3"
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      # For internal docker network
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  krakend:
    image: devopsfaith/krakend
    volumes:
      - ./config/krakend:/etc/krakend
    environment:
      - KAFKA_BROKERS=kafka:9092
    command: ["run", "-c", "/etc/krakend/krakend.json", "-d"]
    ports:
      - "1234:1234"
      - "8080:8080"
    depends_on:
      - kafka
